---

- name: install epel
  yum:
    name: epel-release

- name: install haproxy
  yum:
    name: haproxy

- name: update haproxy configs
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: add new backend host to haproxy
  systemd:
    name: haproxy
    state: restarted
