---

- hosts: awx
  become: true
  roles:
    - wrk
    - awx

- hosts: backend
  become: true
  roles:
    - nginx

- hosts: haproxy
  become: true
  roles:
    - update-lb
  pre_tasks:
    - name: install epel-release
      yum:
        name: epel-release

    - name: install haproxy
      yum:
        name: haproxy
