---

- hosts: awx
  become: true
  roles:
    - wrk
    - awx

- hosts: backend
  become: true
  tasks:
  - name: install epel
    yum:
      name: epel-release
  
  - name: install nginx
    yum:
      name: nginx
  
  - name: configure nginx
    shell: |
        cat <<EOF > /etc/nginx/conf.d/dummy.conf
        server {
        listen 8080;
          location / {
            return 200 '{"message": "$HOSTNAME is up"}';
            }
         }
        EOF

  - name: add new backend host to haproxy
    systemd:
      name: nginx
      state: restarted

- hosts: haproxy
  become: true
  roles:
    - update-lb
  pre_tasks:
    - name: install epel-release
      yum:
        name: epel-release

    - name: install haproxy
      yum:
        name: haproxy
